[package]
name = "internal-tracing"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde = { version = "*", features = ["derive"], optional = true }
serde_json = { version = "*", optional = true }
ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { version = "0.1.0", optional = true }

[features]
enabled = [ "serde", "serde_json" ]
ocaml_types = [ "ocaml", "ocaml-gen" ]
